name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'  # 每天UTC时间3点运行（北京时间11点）
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: 添加上游仓库
        run: |
          git remote add upstream ${{ secrets.UPSTREAM_REPO }}
          git fetch upstream

      - name: 合并变更
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout main
          git merge upstream/main --no-edit
          git push origin main
